---
services:
  testing:
    build:
      context: .
      target: testing
      dockerfile: Dockerfile
      args:
        - USERNAME=eci-user
    command: ["sh", "-c", "./run-ci"]
    env_file:
      - environments/testing.env
    volumes:
      - type: bind
        source: ~/awk-src
        target: /awk-src
        read_only: false
    profiles:
      - testing


  linting:
    image: github/super-linter:v5
    volumes:
      - ~/awk-src:/tmp/lint
    env_file:
      - environments/linter.env
    environment:
      - RUN_LOCAL=true
      - USE_FIND_ALGORITHM=true
      - VALIDATE_ALL_CODEBASE=true
    profiles:
      - linting

  continuous-integration:
    build:
      context: .
      target: continuous-integration
      dockerfile: Dockerfile
      args:
        - USERNAME=eci-user
    command: ["sh", "-c", "sudo ./run-ci"]
    env_file:
      - environments/testing.env
    profiles:
      - continuous-integration

  developing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
    command: ["sh", "-c", ". /tmp/install &&  nohup /tmp/.sleeping_daemon"]
    env_file:
      - environments/development.env
    volumes:
      - type: bind
        source: ~/.ssh
        target: /home/${USER}/.ssh
        read_only: true
      - type: bind
        source: ~/awk-src
        target: /home/${USER}/awk-src
        read_only: false
    profiles:
      - developing