#!/bin/bash

# Install script for dotfiles
src_dir="\${HOME}/dotfiles/src/${1}"
# Check if the first argument is either 'zsh' or 'bash'
if [ "$1" != "zsh" ] && [ "$1" != "bash" ]; then
  echo "Installation Error:: The first argument must be either 'zsh' or 'bash'."
  exit 1
fi
ident=$(grep "Dotfile installation" < "${HOME}/.${1}rc" | wc -c)
if [ "$ident" -gt 0 ]; then
  . "./src/bash/functions"
  wmsg "Dotfiles are already installed. Delete the existing installation and try again."
  exit 1
fi
update_rc_file() {
cat <<EOF >> "${HOME}/.${1}rc"
# Dotfile installation start
# Source dotfiles_dirs
source "\${HOME}/dotfiles/src/bash/functions"
set -a
source "${src_dir}/env.env"
# Add custom dotfiles
# Add environment variables
[ -f \${HOME}/${1}-src/env.env ] && source \${HOME}/${1}-src/env.env
[ -f \${HOME}/${1}-src/ecr.env.ecr ] && decrypt \${HOME}/${1}-src/ecr.env.ecr
[ -f \${HOME}/${1}-src/ecr.env ] && source \${HOME}/${1}-src/ecr.env && rm \${HOME}/${1}-src/ecr.env
set +a
# Add aliases
source "${src_dir}/aliases"
[ -f \${HOME}/${1}-src/aliases ] && source \${HOME}/${1}-src/aliases
# Add functions
[ -f \${HOME}/${1}-src/functions ] && source \${HOME}/${1}-src/functions
# Add dotfiles bin directory to PATH
export PATH="\${HOME}/dotfiles/bin:\${PATH}"
# Dotfile installation end
EOF
}
git pull origin main
. "./src/bash/functions"
imsg "Installing ${1}..."
update_rc_file "$1"
# Loop through all files in the bin directory and make them executable
for file in ${HOME}/dotfiles/bin/*; do
  if [ -f "\${file}" ]; then
    chmod +x "\${file}"
  fi
done
kmsg "Installation complete."
