#!/bin/bash
echo "============================================================================================="
echo "$(date '+%Y-%m-%d% %H:%M:%S')  [INFO] Welcome to the LOCAL Continuous Integration Test Suite."
echo "============================================================================================="
docker pull github/super-linter:latest
echo "------------------------------------------------------------------------"
echo "$(date '+%Y-%m-%d% %H:%M:%S')  [INFO] Running the linters."
echo "------------------------------------------------------------------------"
linted_tmp_dir="/tmp/$(date '+%M%S')"
export linted_tmp_dir=$linted_tmp_dir
# Create directories
rsync README.md install.sh run-linter "$linted_tmp_dir"
rsync -r ./src "$linted_tmp_dir"

if docker run --rm \
-e RUN_LOCAL=true \
-e USE_FIND_ALGORITHM=true \
--env-file ".github/super-linter.env" \
-v "$linted_tmp_dir":/tmp/lint github/super-linter; then
    echo "$(date '+%Y-%m-%d% %H:%M:%S')  [NOTICE] Linting Tests ==> PASSED."
else
    echo "$(date '+%Y-%m-%d% %H:%M:%S')  [NOTICE] Linting Tests ==> FAILED."
    exit 1
fi

rm -rf "$linted_tmp_dir"
