#!/bin/bash

# shellcheck disable=SC1091
[ -f "${HOME}/dotfiles/src/bash/functions" ] && . "${HOME}/dotfiles/src/bash/functions"
imsg "Welcome to the LOCAL Continuous Integration Test Suite."
docker pull github/super-linter:latest
imsg "Running the linters."
tmp_dir="/tmp/$(date '+%M%S')"
export tmp_dir="$tmp_dir"
# Create directories
rsync README.md install run-linter "$tmp_dir"
rsync -r ./src ./.github "$tmp_dir"
# Run Docker
if docker run --rm \
-e RUN_LOCAL=true \
-e USE_FIND_ALGORITHM=true \
--env-file ".github/super-linter.env" \
-v "${tmp_dir}:/tmp/lint" github/super-linter; then
    kmsg "Linting Tests ==> PASSED."
else
    emsg "Linting Tests ==> FAILED."
    exit 1
fi

rm -rf "$tmp_dir"
