#!/bin/bash

# Script to update the current dotfiles installation

# Check if the first argument is either 'zsh' or 'bash'
if [ "$1" != "zsh" ] && [ "$1" != "bash" ]; then
  echo "Update Error:: The first argument must be either 'zsh' or 'bash'."
  exit 1
fi

# Check if the dotfiles are installed
ident=$(grep "Dotfile installation" < "${HOME}/.${1}rc" | wc -c)
if [ "$ident" -eq 0 ]; then
  echo "Update Error:: Dotfiles are not installed."
  exit 1
fi

# Update dotfiles
git checkout production && git pull

# Remove dotfiles from rc file
if [ "$1" == "zsh" ]; then
    sed -i '' '/Dotfile installation start/,/Dotfile installation end/d' "${HOME}/.${1}rc"
else
    sed -i '/Dotfile installation start/,/Dotfile installation end/d' "${HOME}/.${1}rc"
fi

# Install dotfiles
./install "$1"

. "./src/bash/functions"
kmsg "Update complete."
