#!/bin/bash


# Print color coded messages
msg() {
  timestamp=$(TZ="America/St_Lucia" date '+%Y-%m-%d %H:%M:%S')
  case $1 in
    fail)
      printf "\n%s  \033[1;31m[  FAILURE  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    ok)
      printf "\n%s  \033[1;32m[  SUCCESS  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    warn)
      printf "\n%s  \033[1;33m[  WARNING  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    info)
      printf "\n%s  \033[1;34m[INFORMATION]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    *)
      printf "\n%s  [  NOTICE  ] %s\n\n"  "$timestamp" "$2"
      ;;
  esac
}
emsg() {
  msg "fail" "$1"
}
kmsg() {
  msg "ok" "$1"
}
imsg() {
  msg "info" "$1"
}
wmsg() {
  msg "warn" "$1"
}


# A greeting script
greet() {
  # Get the current hour
  timestamp=$(TZ="America/St_Lucia" date '+%Y-%m-%d %H:%M:%S')
  HOUR=$(TZ="America/St_Lucia" date +%H)
  # If the hour is less than 12, it's morning
  if [ "$HOUR" -lt 12 ]; then
    printf "%s Good Morning" "$timestamp"
    # If the hour is between 12 and 18, it's afternoon
  elif [ "$HOUR" -lt 18 ]; then
    printf "%s Good Afternoon" "$timestamp"
    # Otherwise, it's evening
  else
    printf "%s Good Evening" "$timestamp"
  fi
}


# Change directory and list contents
cl() {
  cd "$@" && ll
}


# Extract archive using the correct program
extract() {
  imsg "Extracting $1 ..."
  if [ -f "$1" ] ; then
    case "$1" in
      *.tar.bz2)   tar xjf "$1"     ;;
      *.tar.gz)    tar xzf "$1"     ;;
      *.bz2)       bunzip2 "$1"     ;;
      *.rar)       unrar e "$1"     ;;
      *.gz)        gunzip "$1"      ;;
      *.tar)       tar xf "$1"      ;;
      *.tbz2)      tar xjf "$1"     ;;
      *.tgz)       tar xzf "$1"     ;;
      *.zip)       unzip "$1"       ;;
      *.Z)         uncompress "$1"  ;;
      *.7z)        7z x "$1"        ;;
      *)           wmsg "I don't know how to extract '$1'..." ;;
    esac
  else
    emsg "'$1' is not a valid archive file!"
  fi
}


# Git add commit and push
gacp() {
  imsg "Pushing all changes to GitHub..."
  git add . && git commit -m "$1" && git push && kmsg "Push completed succssfully."
  [ ! $? ] && emsg "Push failed."
}


# Create default directories
make_default_directories() {
  makedir() {
    if [ ! -d "${HOME}/$1" ]; then
      imsg "Creating the $1 directory..."
      mkdir -p "${HOME}/$1"
    fi
  }
  # shellcheck disable=SC3030
  directories=( Downloads bin lib src pysrc )
  # shellcheck disable=SC3054
  for dir in "${directories[@]}"; do
    makedir "$dir"
  done
}


# Make a python virtual environment
python_venv() {
  # shellcheck disable=SC1091
  python -m venv "$1" && . "$1/bin/activate"
}


# Encrypt file using openssl
encrypt() {
 imsg "Encrypting $1..."
 openssl aes-256-cbc -pbkdf2 -e -in "$1" -out "$1".ecr
 [ -f "$1.ecr" ] && rm -f "$1" && chmod 0700 "$1.ecr" && kmsg "$1 encrypted successfully."
 if [ ! $? ] || [ ! -f "$1.ecr" ]; then
  emsg "Encryption failed."
 fi
}


# Decrypt file using openssl
decrypt() {
  imsg "Decrypting ${1}..."
  outfile="${1//.ecr/}"
  openssl aes-256-cbc -pbkdf2 -d -in "$1" -out "$outfile"
  [ -f "$outfile" ] && kmsg "Decryption successful."
  [ ! $? ] && emsg "Decryption failed"
}


# Set environment
setenv() {
  imsg "Setting environment variables from file: $1"
  set -a
  # shellcheck disable=SC1090
  [ -f "$1" ] && . "$1" && kmsg "Environment successfully set." && set +a
  [ ! $? ] || [ ! -f "$1" ] && emsg "An error occurred. Likely file not found." && set +a
}


gen_secret_key() {
  # shellcheck disable=SC2005
  echo "$(openssl rand -base64 32)"
}

purge_docker() {
  imsg "Purging all docker containers and images..."
  docker rm -f "$(docker ps -aq)" && docker rmi -f "$(docker images -q)" && kmsg "Purge completed successfully."
  [ ! $? ] && emsg "Purge failed."
}

# Run functions
make_default_directories
