#!/usr/bin/env bash


# Print color coded messages
msg() {
  timestamp=$(TZ="America/St_Lucia" date '+%Y-%m-%d %H:%M:%S')
  case $1 in
    fail)
      printf "\n%s  \033[1;31m[  FAILURE  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    ok)
      printf "\n%s  \033[1;32m[  SUCCESS  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    warn)
      printf "\n%s  \033[1;33m[  WARNING  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    info)
      printf "\n%s  \033[1;34m[INFORMATION]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    *)
      printf "\n%s  [  NOTICE  ] %s\n\n"  "$timestamp" "$1"
      ;;
  esac
}
emsg() {
  msg "fail" "$1"
}
kmsg() {
  msg "ok" "$1"
}
imsg() {
  msg "info" "$1"
}
wmsg() {
  msg "warn" "$1"
}


# A greeting script
greet() {
  # Get the current hour
  timestamp=$(TZ="America/St_Lucia" date '+%Y-%m-%d %H:%M:%S')
  HOUR=$(TZ="America/St_Lucia" date +%H)
  # If the hour is less than 12, it's morning
  if [ "$HOUR" -lt 12 ]; then
    printf "%s Good Morning" "$timestamp"
    # If the hour is between 12 and 18, it's afternoon
  elif [ "$HOUR" -lt 18 ]; then
    printf "%s Good Afternoon" "$timestamp"
    # Otherwise, it's evening
  else
    printf "%s Good Evening" "$timestamp"
  fi
}


# Change directory and list contents
cl() {
  cd "$@" && ll
}


# Extract archive using the correct program
extract() {
  imsg "Extracting $1 ..."
  if [ -f "$1" ] ; then
    case "$1" in
      *.tar.bz2)   tar xjf "$1"     ;;
      *.tar.gz)    tar xzf "$1"     ;;
      *.bz2)       bunzip2 "$1"     ;;
      *.rar)       unrar e "$1"     ;;
      *.gz)        gunzip "$1"      ;;
      *.tar)       tar xf "$1"      ;;
      *.tbz2)      tar xjf "$1"     ;;
      *.tgz)       tar xzf "$1"     ;;
      *.zip)       unzip "$1"       ;;
      *.Z)         uncompress "$1"  ;;
      *.7z)        7z x "$1"        ;;
      *)           wmsg "I don't know how to extract '$1'..." ;;
    esac
  else
    emsg "'$1' is not a valid archive file!"
  fi
}


# Git add commit and push
gacp() {
  # This function automates the process of adding, committing, and pushing changes to a Git repository.
  # It takes an optional commit message as the first command-line argument. If no message is provided, it uses "minor update" as the default message.
  # It also accepts an optional -u flag to set the upstream origin to the current branch.

  # Default commit message
  message="minor update"

  # If there is an argument, set the message to the argument

  # Check if the first argument is a commit message or an option
  if [[ $# -gt 0 ]]; then
    message=$1
  fi

  # Add all changes to the staging area
  imsg "Adding changes to the staging area..."
  (git add . && kmsg "Changes added to staging area.") || emsg "Failed to add changes to the staging area."

  # Commit the changes
  imsg "Committing changes..."
  (git commit -m "$message" && kmsg "Changes committed.") || emsg "Failed to commit changes."

  imsg "Pushing all changes to the GitHub repository..."
  # Check if the upstream origin should be set
  {
    (git push && kmsg "Push completed.") \
    || \
    ( \
      git push --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)" \
      && \
      kmsg "Push and set upstream completed." \
    ) \
    || \
    emsg "Failed to push changes to the remote repository."
    # Push the changes to the remote repository
  }
}


gres() {
  # This script replaces a pattern in a file, but does not change
  # the original file.

  # Usage:
  # 	gres pattern replacement file

  if [ $# -lt "3" ]; then
    emsg "Usage: gres pattern replacement file"
    else
      pattern=$1
      replacement=$2
      file=$3
    if [ ! -f "$file" ]; then
      emsg "$file is not a file."
      else
        # Use a null byte as the separator, which is unlikely to appear in the file.
        sed "s${IFS}${pattern}${IFS}${replacement}${IFS}g" "$file"
    fi
  fi
}


# Create default directories
make_default_directories() {
  makedir() {
    if [ ! -d "${HOME}/$1" ]; then
      imsg "Creating the $1 directory..."
      mkdir -p "${HOME}/$1"
    fi
  }
  # shellcheck disable=SC3030
  directories=( Downloads bin lib src )
  # shellcheck disable=SC3054
  for dir in "${directories[@]}"; do
    makedir "$dir"
  done
}


# Make a python virtual environment
pyvenv() {
  # shellcheck disable=SC1091
  python -m venv "$1" && . "$1/bin/activate"
}


# Encrypt file using openssl
encrypt() {
 imsg "Encrypting $1..."
 openssl aes-256-cbc -pbkdf2 -e -in "$1" -out "$1".ecr
 [ -f "$1.ecr" ] && rm -f "$1" && chmod 0700 "$1.ecr" && kmsg "$1 encrypted successfully."
 if [ ! $? ] || [ ! -f "$1.ecr" ]; then
  emsg "Encryption failed."
 fi
}


# Decrypt file using openssl
decrypt() {
  imsg "Decrypting ${1}..."
  outfile="${1//.ecr/}"
  openssl aes-256-cbc -pbkdf2 -d -in "$1" -out "$outfile"
  [ -f "$outfile" ] && kmsg "Decryption successful."
  [ ! $? ] && emsg "Decryption failed"
}


# Set environment
setenv() {
  imsg "Setting environment variables from file: $1"
  set -a
  # shellcheck disable=SC1090
  [ -f "$1" ] && . "$1" && kmsg "Environment successfully set." && set +a
  [ ! $? ] || [ ! -f "$1" ] && emsg "An error occurred. Likely file not found." && set +a
}


gen_secret_key() {
  # shellcheck disable=SC2005
  echo "$(openssl rand -base64 32)"
}

purge_docker() {
  imsg "Purging all docker containers, images, and volumes..."
  docker system prune -a && docker volume prune -a && kmsg "Purge completed successfully."
  [ ! $? ] && emsg "Purge failed."
}

# Docker compose functions
# Start, stop, build, and up docker-compose services
dcpu() {
  docker compose --profile "$1" up
}

dcpd() {
  docker compose --profile "$1" down
}

dcpb() {
  docker compose --profile "$1" build
}

dcpub() {
  docker compose --profile "$1" up --build
}

dcpud() {
  docker compose --profile "$1" up -d
}
# Run functions
make_default_directories
