#!/usr/bin/env bash

# Shared message functions. Sourcing this file performs no terminal setup.
# Print color coded messages
msg() {
  timestamp=$(TZ="America/St_Lucia" date '+%Y-%m-%d %H:%M:%S')
  case $1 in
    fail)
      printf "\n%s  \033[1;31m[  FAILURE  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    ok)
      printf "\n%s  \033[1;32m[  SUCCESS  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    warn)
      printf "\n%s  \033[1;33m[  WARNING  ]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    info)
      printf "\n%s  \033[1;34m[INFORMATION]\033[0m %s\n\n" "$timestamp" "$2"
      ;;
    *)
      printf "\n%s  [  NOTICE  ] %s\n\n"  "$timestamp" "$1"
      ;;
  esac
}
emsg() {
  msg "fail" "$1"
}
kmsg() {
  msg "ok" "$1"
}
imsg() {
  msg "info" "$1"
}
wmsg() {
  msg "warn" "$1"
}
